### ISSUE TITLE
Using datetime on x axis doesn't work

### ISSUE THREAD

**Issue by Hofsmo** [nschloe/matplotlib2tikz#149]
Hi,
I wanted to create a plot with dates on the x-axis. However, matplotlib2tikz only accepts floats for axis values. Below I have provided an example of a working pgf code demonstrating what I expected, and also the python code that failed.

Here is a MWE using pgf:
```latex
\documentclass{standalone}

\usepackage{pgfplots}
\usepgfplotslibrary{dateplot}

\begin{document}
	\begin{tikzpicture}
		\begin{axis}[no markers, date coordinates in=x,
				xticklabel=\hour:\minute]
		\addplot coordinates {
			(2016-10-10 18:00, 50.00)
			(2016-10-10 18:15, 50.02)
		};
		\end{axis}
	\end{tikzpicture}
\end{document}
```

Here is a MWE in Python that produces the desired output with show(), but fails using the matplotlib2tikz save function:

```python
import datetime as date
import matplotlib.pyplot as plt
from matplotlib import dates
from matplotlib2tikz import save as plt2tikz

values = [50, 50.02]
time= [date.datetime(2016, 10, 10, 18, 00),
         date.datetime(2016, 10, 10, 18, 15)]
plt.plot(time, values)
hfmt = dates.DateFormatter('%H:%M')
ax = plt.gca() 
ax.xaxis.set_major_formatter(hfmt)

plt2tikz('test.tikz')
```

[dateplot_test.pdf](https://github.com/nschloe/matplotlib2tikz/files/861410/dateplot_test.pdf)

**Comment by tgy** [comment]
I have this problem too :/

**Comment by arbolis** [comment]
I have a similar problem. I'm trying Matplotlib2tikz for the first time and I'm unable to produce a file.tex that should contain dates on the x-axis instead of say floats or ints. I get the error message:

```
Please add the following lines to your LaTeX preamble:

\usepackage[utf8]{inputenc}
\usepackage{fontspec} % This line only for XeLaTeX and LuaLaTeX
\usepackage{pgfplots}
=========================================================
Horizontal alignment will be ignored as no 'x tick label text width' has been passed in the 'extra' parameter
Horizontal alignment will be ignored as no 'y tick label text width' has been passed in the 'extra' parameter
Traceback (most recent call last):

  File "<ipython-input-2-b0ac434fea52>", line 1, in <module>
    runfile('file.py', wdir='some_path')

  File "Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "file.py", line 151, in <module>
    tikz_save('file.tex')

  File "Anaconda3\lib\site-packages\matplotlib2tikz\save.py", line 197, in save
    code = get_tikz_code(*args, **kwargs)

  File "Anaconda3\lib\site-packages\matplotlib2tikz\save.py", line 160, in get_tikz_code
    data, content = _recurse(data, figure)

  File "Anaconda3\lib\site-packages\matplotlib2tikz\save.py", line 283, in _recurse
    data, children_content = _recurse(data, child)

  File "Anaconda3\lib\site-packages\matplotlib2tikz\save.py", line 302, in _recurse
    data, cont = line2d.draw_line2d(data, child)

  File "Anaconda3\lib\site-packages\matplotlib2tikz\line2d.py", line 148, in draw_line2d
    content.append('%.15g %.15g\n' % (x, y))

TypeError: must be real number, not datetime.datetime
```
Does this mean Matplotlib2tikz is currently unable to produce plots with dates as axis labels instead of "real numbers"? If so, is there an easy fix? I don't mind having to modify line2d.py if someone guide me.

I tried to comment lines 136 to 149 of line2d.py, that is:
    '''if has_mask:
        # matplotlib jumps at masked images, while PGFPlots by default
        # interpolates. Hence, if we have a masked plot, make sure that
        # PGFPlots jumps as well.
        data['extra axis options'].add('unbounded coords=jump')
        for (x, y, is_masked) in zip(xdata, ydata, ydata.mask):
            if is_masked:
                content.append('%.15g nan\n' % x)
            else:
                content.append('%.15g %.15g\n' % (x, y))
    else:
        for (x, y) in zip(xdata, ydata):
            content.append('%.15g %.15g\n' % (x, y))
    content.append('};\n')'''

which fixed the error message and even produced a file.tex although I got many "Horizontal alignment will be ignored as no 'y tick label text width' has been passed in the 'extra' parameter" messages.
But I couldn't compile my latex file with the \input{file.tex} statement. I get the error message "! LaTeX Error: Environment groupplot undefined." which I fixed by adding \usepgfplotslibrary{groupplots} in the master tex file, but then I still get another error message: ! File ended while scanning use of \pgfplotstablecollectoneargwithpreparecatcod. I gave up there, as I think I shouldn't force things that much. 

Another attempt: replace the line "content.append('%.15g %.15g\n' % (x, y))" by "content.append((x, y))" yields exactly the same errors as with commenting the whole block.

Another attempt: replace the line "content.append('%.15g %.15g\n' % (x, y))" by "content.append(str(x) + ' ' + str(y) + '\n')", which if I understand well, should mimic the original idea. This times this creates the file.tex although with the warning "Horizontal alignment will be ignored as no 'x tick label text width' has been passed in the 'extra' parameter" for both x and y tick labels. I cannot compile the main latex file due to "! TeX capacity exceeded, sorry [main memory size=8000000]." which is strange because if I use Matplotlib to produce a .pgf file instead of Matplotlib2tikz to produce a .tex file, I haven't this memory issue. The file.tex produced is about 4.5 MB which is way too high. This file has over 171k lines. Maybe it's because my plots are based on some data files with thousands of lines, but then I don't understand why I don't have any memory or speed problem to plot when using Matplotlib to pgf.
By manually removing thousands of lines from the output file.tex, I don't have the memory issue anymore, but I have the error "! Package PGF Math Error: Could not parse input '2017-03-10' as a floating point number, sorry. The unreadable part was near '-03-10'.." so it seems Matplotlib2tikz really wants floats on the x-axis. So my fix is not enough, there are other part(s) in the code to fix, but here I'm at a loss.

**Comment by TaylanT** [comment]
same problem here. Is there a fix or a workaround for this issue?

**Comment by bukhsh** [comment]
same problem...I changed the index within Python, and then manually fixed datetime ticks in tikz...a fix would be very helpful.

**Comment by nschloe** [comment]
You'll need `\usepgfplotslibrary{dateplot}` in the LaTeX header.

**Comment by samarthiith** [comment]
Hi,
Is this fixed? I tried to get to work, it just takes float for x-axis.
Probably I don't understand the fix. Including  `\usepgfplotslibrary{dateplot}` in latex header, how will it know which figures have datetime in x-axis and which don't?

**Comment by tgy** [comment]
@samarthiith are you used datetime objects in your x-axis? I expect you checked the type but asking nevertheless.

**Comment by samarthiith** [comment]
Its a pandas dataframe that I am trying to plot with index being datetime.
I am attaching the tikz file being created (converting it to txt for attaching here).

[loadShiftDE.txt](https://github.com/nschloe/tikzplotlib/files/3446886/loadShiftDE.txt)

![loadShiftDE](https://user-images.githubusercontent.com/9819174/62131718-fb95ef00-b2db-11e9-9502-547d5e62186e.png)

**Comment by tgy** [comment]
It looks like it's already using datetimes on the x-axis. It's just not repeating the printing of the month of year, no?

**Comment by samarthiith** [comment]
yeah, this is plot that is made in matplotlib (it works as expected). I would like to create the tikz file to create this plot in latex. The tikz file attached shows that the x-axis is now float values.

**Comment by tgy** [comment]
Maybe share the python code that generates the TikZ plot. Hard to figure out what's happening with that

**Comment by samarthiith** [comment]
Hmm... I think, Its not clear what I am trying to do. I have some plots that I normally make within python using matplotlib. However, Now I am trying to transfer them to TikZ plot. For which I have a code making the plot and then try to make a tikz file for example: 
`load_c_wk.plot(label='load: 2016')
load_c_wk_ad.plot(label='load: 2016 \nweather: 2015')
plt.xlabel('')
plt.ylabel('Load [GW]')
plt.legend()
tikzplotlib.save('/loadShiftDE.tikz')`
I then include this in my latex document to render the graph there.
