### ISSUE TITLE
Cannot pass extra_axis_parameters

### ISSUE THREAD

**Issue by Steffen1989** [nschloe/matplotlib2tikz#231]
Whenever I run tikz_save(), I get the annoying messages:
```
Horizontal alignment will be ignored as no 'x tick label text width' has been passed in the 'extra' parameter
```
To get rid of them, I need to pass another argument extra_axis_parameters={...}
which is supposed to be of type 'set' to tikz_save.

This input variable is then used in axes.py to define the variable tick_label_text_width (l. 410-414)
```
    if tick_label_text_width_identifier in data['extra axis options']:
        tick_label_text_width = data['extra axis options [base]'][
                    tick_label_text_width_identifier
                    ]
del data['extra axis options'][tick_label_text_width_identifier]
```

The variable `data['extra axis options [base]']` however is also of type `set`, therefore causing a
```
TypeError: 'set' object is not subscriptable
```
Am I doing something wrong or is this a bug?

This is the command that I use:
```
    tikz_save(directory + data_name[:-4] + '.tex',
            figureheight='\\figureheight',
            figurewidth='\\figurewidth',
            extra_axis_parameters={
##                'x tick label text width={\\textwidth}',
                'x tick label text width',
                '10 pt',
                },
            show_info=False,
            )
```

**Comment by tgrandje** [comment]
@Steffen1989 I had the same trouble... I tried the following :
`tikz_save(
    ....,
    extra_axis_parameters={
                        'x tick label text width={\\textwidth}', 
                        'y tick label text width={\\textwidth}',
                        }
    )`

And made one change on line 410 of matplotlib2tikz\axes.py :
`if any([tick_label_text_width_identifier in x for x in data["extra axis options"]]):`
instead of 
`if tick_label_text_width_identifier in data["extra axis options"]:`

The following lines of the code, calling data["extra axis options [base]"][tick_label_text_width_identifier] are only compatible with a dictionnary instead of a set ; this seems to be the opposite of what de doc strings specifies...

I don't know if this may damage the output in any other way (I haven't been able to produce my output yet for different reasons...)

**Comment by tgrandje** [comment]
@Steffen1989 
Same problem here. The trouble seems to be in _get_label_rotation_and_horizontal_alignment inside \matrplolib2tikz\axes.py.
data["extra axis options"] is handled as if it where a dictionnary which it is not.
I replaced 
`
if tick_label_text_width_identifier in data["extra axis options"]:
        tick_label_text_width = data["extra axis options [base]"][
            tick_label_text_width_identifier
        ]
        del data["extra axis options"][tick_label_text_width_identifier]
`
by 
`
for option in data["extra axis options"].copy():
        if tick_label_text_width_identifier in option:
            tick_label_text_width = option.split('=')[-1]
            data["extra axis options"].remove(option)
`
It seems to be working (I'm not sure yet, I might try to pull a request after verifications).

**Comment by nschloe** [comment]
It's fixed now. (Also I removed the annoying messages.)
